### ISSUE TITLE
Agregar NoInfo=1 a los NPC

### ISSUE THREAD

**Issue by plusin** [ao-org/argentum-online-server#563]
Nos gustaría tener la posibilidad de agregar al NPC.dat el valor NoInfo=1 para que los NPC no aparezcan en la info del Mapa, gracias.

**Comment by Centorios** [comment]
#564

**Comment by Centorios** [comment]
https://github.com/ao-org/argentum-online-client/pull/354

**Comment by plusin** [comment]
Gracias!!
