### ISSUE TITLE
[FEATURE] Agregarle fecha y hora a la consulta que nos llegan al PanelGM

### ISSUE THREAD

**Issue by plusin** [ao-org/argentum-online-server#570]
Necesitamos que por favor al momento de registrar una consulta que llega por /GM en alguna parte del panel nos aparezca fecha y hora en la que se generó dicha consulta.

**Comment by juanitonelli** [comment]
Resuelto en:
https://github.com/ao-org/argentum-online-server/pull/606#pullrequestreview-2195066205
https://github.com/ao-org/argentum-online-client/pull/376#pullrequestreview-2195068900

![351435138-144cc3b0-d5b9-443b-a726-e1f0b0202b17](https://github.com/user-attachments/assets/ce2591c4-89a1-4b52-9a46-353bb4a86119)

**Comment by plusin** [comment]
El panel de GM esta bug, respondes / borras consultas, y al actualizar, vuelven a aparecer

![image](https://github.com/user-attachments/assets/ded0e48a-8889-405a-882a-1d5185cd4767)

![image](https://github.com/user-attachments/assets/379ebe3c-fe14-4cb0-9eb5-b827f134a203)

![image](https://github.com/user-attachments/assets/c50bf4fa-497b-4995-b3c4-e2b3bd991219)

**Comment by juanitonelli** [comment]
Lo creé en su propia issue para trackear el branch.
https://github.com/ao-org/argentum-online-server/issues/611
