### ISSUE TITLE
[FEATURE] - Recordar más de 1 cuenta en el cliente

### ISSUE THREAD

**Issue by plusin** [ao-org/argentum-online-server#669]
# Recordar más de 1 cuenta en el cliente

## Resumen

El usuario lauty a través de Discord sugiere que sumaría bastante tener la posibilidad de que el cliente recuerde más de 1 email en el inicio del cliente, de esta manera, aquellos que tienen varios emails pueden tener esa comodidad.

**Comment by RecoX** [comment]
Esto no lo vamos a realizar, por que supone un riesgo de seguridad para el proyecto.

Cada persona es responsable de guardar sus credenciales de manera segura.
